# -*- coding: utf-8 -*-
"""Simple-name-bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2Y2GkzWeamJJFIRvx2NmJSv8tssFrjI
"""

name = input("please type your name: ")
age = input("please type your age: ")
print("Hi" ,name, "you are" ,age, "years old, nice to meet you")